version: "2"

services:
     ssr:
        container_name: ssr
        #image: kdaye/shadowsocksr
        image: registry.cn-hangzhou.aliyuncs.com/kj/shadowsocksr
        ports:
                - "1080:1080/tcp"
                - "1080:1080/udp"
                - "1081:1081/tcp"
        volumes:
                - ./config.json:/etc/config.json
