version: "2"

services:
     ssr:
        container_name: ssr
        #image: kdaye/shadowsocksr
        image: registry.cn-hangzhou.aliyuncs.com/kj/shadowsocksr
        ports:
                - "1080:1080/tcp"
                - "1080:1080/udp"
        command: ss-redir -s your_server_ip -p 8388 -k passwd -b 0.0.0.0 -l 1080 -m aes-256-cfb -o tls1.2_ticket_auth -O auth_aes128_md5 -u
